#ifndef METAWATCH_IDLE_PAGE_LISTPAIREDDEVICES_H
#define METAWATCH_IDLE_PAGE_LISTPAIREDDEVICES_H

extern const struct IdlePage IdlePageListPairedDevices;

#endif /*  METAWATCH_IDLE_PAGE_LISTPAIREDDEVICES_H */
